apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe-backend
  template:
    metadata:
      labels:
        app: tictactoe-backend
    spec:
      containers:
        - name: backend
          image: akanshab/tictactoe-game-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-backend
spec:
  selector:
    app: tictactoe-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
